- frontend/src/components/AddProgramModal.js
- frontend/src/components/EditProgramModal.js
The missing id caused the label not to toggle the checkbox state.
> Make groups and people clickable

- backend/package-lock.json
- backend/package.json
- backend/server.js
I tried to avoid this, but it seems like the only reasonable option for things like the title or the length of time intervals (#51).
> Add settings endpoint

- frontend/src/Client.js
- frontend/src/components/App.js
- frontend/src/components/Export.js
- frontend/src/components/Import.js
- frontend/src/components/Settings.js
- frontend/src/components/Timetable.js
The time interval can be selected in the Settings tab. The selection is stored in a timetable settings - it is for all users of given timetable. It only affects the displaying of the programs.
> Customizable time intervals

- frontend/src/components/EditProgramModal.js
- frontend/src/components/Program.js
- frontend/src/components/ViewSettings.js
- frontend/src/index.css
- frontend/src/store/viewSlice.js
Each program now has a simple text field for adding program place. In view settings, displaying the place can be toggled.
> Add places

- frontend/src/components/App.js
- frontend/src/components/Export.js
- frontend/src/components/Import.js
- frontend/src/store/settingsSlice.js
Add settings to import and export, fix loading of settings.
> Fix settings

- frontend/cypress/component/Timetable.cy.js
- frontend/src/components/Timetable.js
For testing purposes so that we can set the time.
> Timetable tests

- frontend/cypress/component/Packages.cy.js
- frontend/src/components/Packages.js
Create list of "nice" colors for the timetable:
For compatibility, still allow custom colors:
> Color list

- frontend/cypress/component/People.cy.js
- frontend/src/Client.js
- frontend/src/components/App.js
- frontend/src/components/EditProgramModal.js
- frontend/src/components/Groups.js
- frontend/src/components/Import.js
- frontend/src/components/Packages.js
- frontend/src/components/People.js
- frontend/src/components/Program.js
- frontend/src/components/Ranges.js
- frontend/src/components/Rules.js
- frontend/src/components/Settings.js
- frontend/src/components/Timetable.js
- frontend/src/components/Users.js
Prepare new top-level section for people. In the future, attendance will be tracked here so that if a person is missing on a particular day, the planner will check that there is no program led by this person at that day.
> People section

- vite.config.js
Google auth is configured for this one.
> Update local port

- src/components/Tray.jsx
- src/index.css
Previously, it was hard to guess that you can also drop program to the tray.
> Make tray drop target more prominent

- src/FirestoreClient.js
Public level is integer, cannot be checked like this.
> Fix getting public level

- src/components/App.jsx
- src/components/Blocks.jsx
- src/components/Droppables.jsx
- src/components/EditProgramModal.jsx
- src/components/Export.jsx
- src/components/Program.jsx
- src/components/Rules.jsx
- src/components/Settings.jsx
- src/components/Stats.jsx
- src/components/Timetable.jsx
- src/components/Tray.jsx
Everything is guarded by a feature flag. Just queries, mutations will follow in a separate PR.
> Load programs using RTK query

- src/components/EditProgramModal.jsx
This way, state is initialized only in case program is fully loaded.
> Create edit modal wrapper

- src/FirestoreClient.js
- src/store/groupsApi.js
- src/store/packagesApi.js
- src/store/peopleApi.js
- src/store/publicLevelApi.js
- src/store/rulesApi.js
- src/store/settingsApi.js
- src/store/timetableApi.js
- src/store/usersApi.js
Except for programs - there will be a separate PR.
> Add streaming updates

- eslint.config.mjs
> Add tsx files to eslint config

- src/components/NavBar.jsx
- src/components/TimetableV2.tsx
**Fixes some of #725:** 
- Filters on the top - remove them since it doesn't work
- Printing - removes bottom bar
- Program swap - works a bit differently than previous version
- Looks like this is failing due to data inconsistency. There is no guarantee that `people.find(...)` will succeed, so there needs to be some fallback in `person!.name`. _Originally posted by @janzarsky in https://github.com/janzarsky/scout-planner/pull/708#discussion_r1854232383_
> Timetable v2: Enhancements

- cypress/component/EditProgramModal.cy.jsx
- src/components/EditProgramModal.jsx
- src/store/peopleApi.js
> Set new person as attending

- cypress/component/Timetable.cy.jsx
- src/components/Timetable.jsx
- src/helpers/EmptyDays.js
- src/helpers/EmptyDays.test.js
- src/helpers/TimetableSettings.js
> Hide extra days when printing

- src/components/TimetableV2.tsx
- src/index.css
Fixes some of https://github.com/janzarsky/scout-planner/issues/725:
- **Timetable v2: Show non-owners**
- **Timetable v2: Add people filter**
- **Timetable v2: Handle concurrent blocks (blockOrder)**
> Timetable v2: Enhancements - part 2

- .github/workflows/build_frontend.yml
- .github/workflows/deploy_functions.yml
- eslint.config.mjs
- functions/.gcloudignore
- functions/.gitignore
- functions/index.js
- functions/index.test.js
- functions/package-lock.json
- functions/package.json
Functionality to be added later, this is to setup the directory, etc.
> Add cloud function for cloning timetable

- client/cypress/component/Timetable.cy.jsx
- client/src/components/Droppables.jsx
- client/src/store/settingsApi.js
> Add group lock for Droppables

- client/cypress/component/Timetable.cy.jsx
- client/src/components/Program.jsx
> Add group locking to program swap

- client/src/components/TimeIndicator.jsx
> Fix moving of time indicator

- .github/workflows/deploy_functions.yml
- functions/.gcloudignore
- functions/.gitignore
- functions/build.cjs
- functions/package-template.json
- functions/package.json
- functions/src/index.js
- package-lock.json
The approach with package.json template is a hack, but could not find anything better.
> Bundle functions

- client/.prettierignore
- client/src/index.css
> Use prettier for CSS

- client/src/components/TimetableV2/ComposeSchedule.tsx
- client/src/components/TimetableV2/index.tsx
- **Timetable V2: hard groups filtering and skip empty days**
- **Timetable V2: Correct virtual group handling**
- **Fix dependency array in useCallback for navigate function**
> Timetable v2: minor enhancements

- client/src/store/shiftApi.js
> Add shift API

- client/src/components/Clone.jsx
- client/src/components/Shift.jsx
> Add vertical spacing in settings

- client/src/components/Import.jsx
- common/src/importer.js
> Handle import errors

- client/src/components/EditProgramModal.jsx
- client/src/components/Packages.jsx
To address common issues with timetable printing.
> Add hints how to save space in timetable
